### ISSUE TITLE
Browsers no longer show organization name for EV certificates

### ISSUE THREAD

**Issue by mimi89999** [MovingToHTTPS/movingtohttps.com#6]
The claim in https://github.com/MovingToHTTPS/movingtohttps.com/blob/master/index.html#L183 not true anymore
https://blog.mozilla.org/security/2019/10/15/improved-security-and-privacy-indicators-in-firefox-70/

**Comment by stilliard** [comment]
Hi @mimi89999 
Great point, thanks for catching that. 
This is now updated with the link you provided for anyone to read more about too, thanks!
